on: [push, pull_request]
name: Continuous Integration
jobs:
  build:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1.1.0

    - name: Test
      run: make test

    - name: Publish coverage
      uses: coverallsapp/github-action@v1.0.1
      with:
        path-to-lcov: ./build/reports/coverage/lcov.info
        github-token: ${{ secrets.GITHUB_TOKEN }}
